service: serverless-webapp
frameworkVersion: ">=1.29.2 <2.0.0"

plugins:
- serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  region: ap-northeast-1

package:
  exclude:
    - .circleci/**
    - .git/**
    - bin/**
    - test/**
    - docs/**
    - .*
    - package-lock.json
    - yarn.lock
    - package.json
    - README.md
    - media

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{any+}
          method: get
