defaultHandler:
  lib/default.handler
meta:
  sitetitle: Welcome to serverless!
sitemap:
  /:
    title: Welcome!
    template: index.html
  /hello:
    title: Hello World
    template: index.html
  /about:
    title: About us
    template: index.html