site_meta:
  url: https://example.com
  title: Welcome to serverless!
  description: Serverless website.
  twitter:
    card: summary_large_image
  ogp:
    type: website
    image: https://example.com/ogp.png
sitemap:
  /:
    title: Welcome!
    handler: lib/default.handler # Default value
    template: default.html # Default value
  /hello:
    title: Hello World
  /about:
    title: About us
settings:
  defaultHandler: lib/default.handler
